Repository danielknobe/blobbyvolley2, pull requests merged in 2022-10, with the labels that each got.

#50 Header Check
  .github/workflows/compilers.yaml
  src/CMakeLists.txt
  src/MatchEvents.h
  src/test_compile.cpp.in
  src/test_compile_main.cpp
Labels: ci

#57 clock code based on `<chrono>`
  src/Clock.cpp
  src/Clock.h
  src/DuelMatch.cpp
  src/DuelMatch.h
  src/state/GameState.cpp
  src/state/ReplayState.cpp
Labels: code cleanup

#53 Android CI
  .github/workflows/android.yaml
  src/main.cpp
  src/server/DedicatedServer.cpp
Labels: ci, android

#60 Fixing base64
  src/base64.cpp
  src/base64.h
  test/Base64Test.cpp
  test/CMakeLists.txt
Labels: ready for merge

#69 removed superfluous class
  src/CMakeLists.txt
  src/InputSourceFactory.cpp
  src/InputSourceFactory.h
  src/state/LocalGameState.cpp
Labels: ready for merge
