Repository danielknobe/blobbyvolley2, pull requests merged in 2023-02, with the labels that each got.

#91 new icon up to 256x256 added and use it with MSVC
  data/Icon.ico
  res.rc
  src/CMakeLists.txt
  win/Installer.iss
  win/icon.ico
  win/res.rc
Labels: enhancement, ready for merge

#93 added missing const
  src/IUserConfigReader.h
  src/UserConfig.cpp
  src/UserConfig.h
Labels: ready for merge

#102 changed argument passing
  src/replays/ReplayRecorder.cpp
  src/replays/ReplayRecorder.h
  src/server/NetworkGame.cpp
  src/state/GameState.cpp
  src/state/NetworkState.cpp
Labels: ready for merge

#103 disentangle InputSource and DuelMatch
  src/DuelMatch.cpp
  src/InputSource.cpp
  src/InputSource.h
  src/ScriptedInputSource.cpp
  src/ScriptedInputSource.h
  src/state/LocalGameState.cpp
  src/state/LocalGameState.h
  src/state/NetworkState.cpp
Labels: ready for merge

#104 fixed bot API bug
  src/IScriptableComponent.cpp
Labels: bug, ready for merge
