Repository danielknobe/blobbyvolley2, pull requests merged in 2023-06, with the labels that each got.

#123 ubuntu 18.04 runner and travis ci removed
  .github/workflows/compilers.yaml
  .github/workflows/main.yaml
  .travis.yml
Labels: ready for merge

#128 finalize italien translation
  data/lang_de.xml
  data/lang_it.xml
Labels: translation, ready for merge

#130 moved union3
  data/scripts/old/Union3.lua
Labels: ready for merge

#129 modification to bot difficulty
  src/ScriptedInputSource.cpp
Labels: ready for merge

#131 fix ci typo (20.04 -> 22.04)
  .github/workflows/main.yaml
Labels: ready for merge

#134 ThreadSafe RakServer wrapper to prevent race conditions
  src/ScriptedInputSource.cpp
  src/UserConfig.cpp
  src/raknet/RakPeer.cpp
  src/server/DedicatedServer.cpp
  src/server/DedicatedServer.h
  src/server/NetworkGame.cpp
  src/server/NetworkGame.h
  src/server/ThreadSafeRakServer.h
  test/Base64Test.cpp
Labels: ready for merge

#135 make sure server uses syslog to get right msg order and timestamps
  src/server/servermain.cpp
Labels: enhancement, ready for merge

#136 fix use of invalid iterator after erase from map
  src/server/DedicatedServer.cpp
Labels: bug, ready for merge
